### ISSUE TITLE
Shebang line in bin/pickanartist

### ISSUE THREAD

**Issue by oalders** [davorg/pickanartist#1]
I checked out the repo and mindlessly ran:

`perl bin/pickanrtist`

that gives 

> Too late for "-CS" option at bin/pickanartist line 1.

which is fine, because I was doing it wrong.

Then I ran 

`./bin/pickanartist`

but that defaults to my system perl and ignores the perl that I have installed via `plenv`, where all of my CPAN modules also get installed.

So I'm wondering if a `#!/usr/bin/env perl` would make sense?

**Comment by davorg** [comment]
Does `/usr/bin/env` allow you to pass arguments like `-CS`? I should know the answer, but I don't think I've ever tried it.

Honestly, you can probably just drop the `-CS` in this case. How many people listen to to artists with weird UTF-8 in their names? :-)

But yeah, `/usr/bin/env perl` is the better approach.

**Comment by oalders** [comment]
> Does /usr/bin/env allow you to pass arguments like -CS? I should know the answer, but I don't think I've ever tried it.

Yeah, I have no idea!

> How many people listen to to artists with weird UTF-8 in their names? :-)

Maybe this one? 

https://open.spotify.com/artist/1TIbqr0x8HoKzKBNtNN8wf?si=3hiTIfyPRXCnJiN8ZScabg&nd=1&dlsi=8254c9486ee84ebc

**Comment by davorg** [comment]
They're just doing that to piss people off. They deserve to have their name mangled.

**Comment by davorg** [comment]
I worked out how to pass arguments to `/usr/bin/env perl`

https://github.com/davorg/pickanartist/commit/accd8029012dc2be5303788fd9fc101d45c26aae
